common.py
tutorials/setup.md

Added/fixed most of the change suggestions for the Novel and Corpus classes. 
Concerning lines 87-89 (find the base path of the repository), I tried to use the source_file_path function from dh_testers/common.py but that didn't give me the base of the repo either. We should discuss this tomorrow.

Added documentation and doc tests to Novel and Corpus classes

---

common.py
tutorials/git_install_setup.md
tutorials/python_install.md
tutorials/setup.md
tutorials/setup_test.py

Abstracted the tutorials to make it more generic so that it can be used across projects, broke up to be Git and Python (leaving the separate setup tutorial alone for now). Python tutorial close to final draft, Git tutorial needs to be fully drafted. I think the Python install file could be made more abstracted and perhaps we don't need ipython as a dependency right now if we're using an IDE.

Tutorial edits and script linting

---

tutorials/git_install_setup.md
tutorials/python_install.md

Minor edits to facilitate directory changes

Edits to Documentation

---

gender_novels/tutorials/coding_style.md
gender_novels/tutorials/git.md
gender_novels/tutorials/git_install_setup.md
gender_novels/tutorials/pycharm_install_setup.md

Thoughts on adding a devbranch again? None of these tutorials are ready for prime time yet.

End of day push. Added parts of the git, pycharm, and coding style tutorials

---

setup.py

fix f-strings in setup.py (should not cause syntax error in py2 or 3.4)

---

gender_novels/tutorials/setup/1_python_install.md

Fixing Windows commands

---

gender_novels/__init__.py
gender_novels/common.py
gender_novels/testing/tests.py

All tests pass, PyCharm 100% happy.  Let's keep it that way.  :-)

Fixed lint errors in common.py and testing

---

.editorconfig
gender_novels/common.py

Additional changes:
- changed line length to 100 characters
- removed strange character from common.py

Removed print statement that had caused a test failure

---

.gitignore
gender_novels/common.py
gender_novels/scratch.py

I staged the scratch file and then added it to gitignore. We'll see if it gets pushed properly.

Added simple novel tokenizer and scratch file

---

gender_novels/tutorials/dataviz_matplotlib.ipynb

Added Jupyter Notebook for session

Intro to Data Visualization (Matplotlib) Jupyter Notebook

---

gender_novels/common.py
gender_novels/novel.py

Also cleaned up imports in common.py

Removed errant "/" that made Windows machines load all texts remotely.

---

gender_novels/tutorials/testing_intro_doctest.ipynb

I added this as a brief tutorial to doctest based on Myke's sessions on Wednesday. Feel free to expand / edit / update but wanted to have something that the students could refer to.

Intro to Testing (doctest) tutorial

---

gender_novels/deployment/app.py
gender_novels/deployment/static/css/index.css
gender_novels/deployment/static/js/clock.js
gender_novels/deployment/templates/index.html
requirements.txt

New requirement: flask
The flask app is setup in debug mode, which means that it will automatically load changes to html files.

Added basic flask app in the deployment folder

---

gender_novels/corpora/sample_novels/texts/chopin_bayoufolk

Added the novel _Bayou _Folk_ by Kate Chopin to the text file directory under corpora.

Added Bayou Folk by Kate Chopin

---

gender_novels/corpora/sample_novels/texts/wells_invisibleman.txt

I pasted text from Project Gutenberg of Invisible Man by H.G. Wells.

add Invisible Man by H.G. Wells

---

gender_novels/corpora/sample_novels/texts/opie_adeline.txt

[DEMO — DON'T MERGE] I'm adding a .txt file to our sample_texts directory

Added Opie novel

---

gender_novels/corpora/sample_novels/sample_novels.csv

Metadata for Opie entry

---

gender_novels/corpora/sample_novels/texts/stevenson_jekyll.txt

Uploading .txt file for Strange Case of Dr. Jekyll and Mr. Hyde by Robert Louis Stevenson. Metadata sent to Stephen. Note line 23 - Gutenberg suggests using a different file which is "much easier to read" - worth examining.

Added Jekyll & Hyde by Stevenson

---

gender_novels/novel.py

Sending an update for get_quoted_text(). It's not perfect, but Elena needs this so she can present text cases

Updated version of get_quoted_text()

---

gender_novels/analysis/analysis.py
gender_novels/deployment/app.py

Also switched flask config so that the startup process would open a browser on the index page when starting up the server.

Added analysis module and analysis.py for the analysis group.

---

gender_novels/corpora/sample_novels/texts/stoker_dracula.txt

[demo] I will add metadata in the next PR

Added Dracula

---

gender_novels/analysis/README.md

The readme preserves the link to the analysis ideas google doc.

Added readme for analysis group

---

gender_novels/tutorials/command_line.md

Adding command line tutorial with basic commands, we can expand on it if we get deeper into commands next week.

Command line tutorial

---

gender_novels/tutorials/command_line.md

Includes:
- relative and absolute paths
- editing files
- man

Added my notes to the command line tutorial

---

gender_novels/analysis/analysis.py
gender_novels/novel.py

Novel.get_word_freq takes one word at a time and returns frequency of the word's appearance from the whole book.
get_comparative_word_freq is in analysis.py and returns the frequencies of words of interest relative to one another.

Added word frequency and comparative frequency functions

---

gender_novels/deployment/readme.md

This is a markdown file that contains the first draft for the information concerning things like "about us" pages and the eggling of a description of our gender novels project. It also has a link to a Google Doc so that people can make suggestions for me to edit/change things if they find errors or simply want to add more info to it.

Added Markdown File for "About Us" Stuff

---

gender_novels/corpora/sample_novels/texts/eastman_phillis.txt
gender_novels/corpora/sample_novels/texts/eastwood_lollard.txt
gender_novels/corpora/sample_novels/texts/eaton_craterlake.txt
gender_novels/corpora/sample_novels/texts/eddy_allisfamily.txt
gender_novels/corpora/sample_novels/texts/edgar_crusaders.txt
gender_novels/corpora/sample_novels/texts/edginton_marriedlife.txt
gender_novels/corpora/sample_novels/texts/edholm_merriweathergirls.txt
gender_novels/corpora/sample_novels/texts/fairless_brotherhilarius.txt
gender_novels/corpora/sample_novels/texts/falkner_moonfleet.txt
gender_novels/corpora/sample_novels/texts/falkner_nebulycoat.txt
gender_novels/corpora/sample_novels/texts/falkner_stadivarius.txt

Books where collected from Project Gutenberg. The meta data was added to the google drive spreadsheet. 11 books taken instead of 9 as complete metadata for two books was not available.

Adding book to corpus

---

gender_novels/corpus_gen.py
requirements.txt

Should be better if there is already a file here to start with for using git and merging stuff?

Add file for coding in

---

gender_novels/corpus_gen.py
gender_novels/novel.py

Outlined a plan for generating the metadata for desired books in generate_corpus_gutenberg.

Plan for generating corpus

---

gender_novels/analysis/analysis.py

Added function which takes a counter object of words and sorts it by part of speech into a dictionary of form {part of speech tag: counter object of words}. For use in conjunction with functions which find all words following "he", "she" to help enable word association.

Added get_counts_by_pos

---

gender_novels/analysis/README.md

This text includes a link to sources that I referenced on Friday when talking about what I have learned about 19th century history and what sort of questions we should be asking. It is the document I put in the analysis Slack in google doc form.

Referenced sources document

---

gender_novels/corpus_gen.py
requirements.txt

Also moved import to function to contain it for the time being.

Removed pywikibot from requirements

---

gender_novels/__init__.py

the testing system only tests files that are imported into the system.  This is the first of several pull requests to do so.  It exposes existing bugs in the tests.

add __init__.py for testing

---

gender_novels/novel.py

The new version uses a Counter to look up the count of a word instead of looking through the text itself.
The Counter, Novel.word_counts, gets initialized on the first lookup.

Faster version of Novel.get_count_of_word()

---

gender_novels/analysis/gender_pronoun_freq_analysis.py
gender_novels/novel.py

Used word counter and frequency functions to get data based on our current corpus. Wrote methods to bin data separated by novel into lists based on metadata categories.

Immediate results

---

gender_novels/deployment/static/markdowns/gender_novels_overview.md

This file is not complete - complete with a cheesy picture of books - but it is a template to use with website formatting. More will be coming soon.

Added Markdown Overview File for Site

---

gender_novels/analysis/analysis.py
gender_novels/analysis/he_she_freq_data.md

This is a markdown file with data Emily and I found from our basic analysis from last week looking at frequencies of male and female pronouns. It includes some numbers as well as explanations about what those numbers mean.

Markdown file about basic analysis

---

gender_novels/analysis/gender_pronoun_freq_analysis.py

I added doctests to all the methods except for the first two. The first two require the ability to make a subcorpus to do a doctest unless the doctest is going to take a couple minutes. Thus, I haven't written doctests yet for those two.
Also, a new analysis has been added to compare subject pronouns vs object pronoun use for masculine and feminine pronouns.
The statements to actually run all of this code and print the results are at the bottom in the main section. They are commented out so you can choose what exactly you would like to run and then uncomment that bit.

Basic pronoun frequency analysis code additions

---

gender_novels/deployment/static/markdowns/gender_novels_analysis.md
gender_novels/deployment/static/markdowns/gender_novels_overview.md

Skeletons of the markdown files for the website. These will be updated with more definite and complete writings as the analysis and data groups finish their research. This is mostly so that the formatting on the website can be finalized and prepared for the final product.

Markdown Skeletons

---

gender_novels/analysis/gender_pronoun_freq_analysis.py

Maps years to lists of pronoun frequencies

Function to sort the frequency date by year

---

gender_novels/corpus.py
gender_novels/novel.py

Also __eq__ and __lt__ for novels required for corpus comparisons and novel sorting.

Addition and comparison functions for corpus

---

.gitignore
gender_novels/common.py
gender_novels/corpus_gen.py
gender_novels/tutorials/gutenberg_module_install.md

Typos are the bane of my existence.

Lots of bugfixes to corpus_gen (including some very important ones)

---

gender_novels/deployment/static/markdowns/gender_novels_analysis.md
gender_novels/deployment/static/markdowns/gender_novels_overview.md

Updated the markdown files for the overview and analysis pages for the deployment group presentations.

Update for Deployment Group Presentation

---

gender_novels/analysis/analysis.py

I hard reset my working direction and added in the necessary changes. everything should be up to date now.

updated doctests, removed unnecessary modifications

---

.gitignore
gender_novels/corpus.py
gender_novels/corpus_gen.py
gender_novels/novel.py

the gutenberg corpus gets downloaded when a user tries to load Corpus('gutenberg')

Added function to download gutenberg corpus

---

gender_novels/tutorials/graph_style.md

Added tutorial for getting graph styles to match

Created gender_novels/tutorials/graph_style.md

---

gender_novels/common.py
gender_novels/tutorials/graph_style.md

Added load_graph_settings method to common.py, updated graph settings tutorial

Updated graph settings methods

---

gender_novels/common.py
gender_novels/pickle_data/README.md

Easy ways to save and restore arbitrary data that takes a long time to create

load_pickle and store_pickle in common.py

---

gender_novels/analysis/gender_pronoun_freq_analysis.py

Changed England to UK because that is how it is formated in the gutenberg corpus metadata. Also added print function to see how close to being done the function is

Changed "England" to "United Kingdom" +added count function

---

gender_novels/common.py
gender_novels/deployment/static/css/base.css

Changed colors for website and background color for graphs to match

Updated base.css, load_graph_settings in common.py

---

gender_novels/deployment/static/markdowns/gender_novels_overview.md

The overview page has been looking rather slim and rusty for awhile now, and this should hopefully fix that. I realize there's still the picture of the book, and I hope that we can throw an example chart followed by an explanation there. Once I get some more write-ups.

An actually polished overview page!

---

gender_novels/analysis/gender_pronoun_freq_analysis.py

Doctests for main analysis methods, pickles implemented, if statements to get test_corpus to still work

Hopefully the same changes but with updated repo

---

gender_novels/corpus.py

Collaboration of Ife, Keith, and Maritza

Added get_sample_text_passages() method

---

gender_novels/deployment/static/markdowns/grammar_writeup.md

Corrected grammar, implemented standard linguistics terms (and provided definitions), and also improved clarity of sentences.

Copy edit and clarity changes to grammar_writeup.md

---

gender_novels/deployment/app.py
gender_novels/deployment/static/js/convertMarkdown.js
gender_novels/deployment/static/markdowns/corpus_scraping.md
gender_novels/deployment/static/markdowns/metadata_acquisition.md

Fixed problems with @ifeife123 ‘s write-up not rendering properly, and figured out how to do relative links.

Fixed Markdown Weirdness

---

gender_novels/deployment/static/markdowns/statistical_analysis.md

Updated statistical_analysis.md to work with the new picture formats

Fixed Imagse in statistical_analysis

---

gender_novels/deployment/static/markdowns/corpus_api.md
gender_novels/deployment/static/markdowns/install_gutenberg.md
gender_novels/deployment/templates/corpus-notes.html

Noticed also that code blocks in Markdowns are coming out funny.  Pictures posted to #general of Slack.  @iRedlon 
@srisi You're fine with people emailing you?

Instructions for Downloading and Updating Corpus

---

gender_novels/deployment/static/css/base.css
gender_novels/deployment/templates/base.html

Navbar should now collapse properly.

Fixed navbar collapse

---

gender_novels/deployment/static/markdowns/corpus_metadata.md
gender_novels/deployment/static/markdowns/dunning_analysis.md
gender_novels/deployment/static/markdowns/grammar_analysis.md
gender_novels/deployment/static/markdowns/install_gutenberg.md
gender_novels/deployment/static/markdowns/instance_distance_analysis.md
gender_novels/deployment/static/markdowns/pronoun_adjective_analysis.md
gender_novels/deployment/static/markdowns/pronoun_frequency_analysis.md
gender_novels/deployment/static/markdowns/subject_object_pronoun_analysis.md
gender_novels/deployment/static/markdowns/web_scraping.md

The biggest fix is to the code blocks; while the syntax highlighting is now gone on the repo, the code on the website is now much more readable now that the line breaks appear.  There are also other formatting fixes.  
Resolves #302 and #299 .

Formatting Fixes

---

.gitignore
gender_novels/corpora/gutenberg_mirror_sample/readme.md
gender_novels/corpus_gen.py
requirements.txt

Makes it possible to generate the text files from the Gutenberg mirror without needing to recreate the Metadata file.

Corpus Gen improvements
